version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # below first we wait_for_db then run the app
    # we will also have to migrate our database before
    # starting the app
    command:  >
      sh -c "python manage.py wait_for_db && 
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      # below we give POSTGRES_DB which is app
      - DB_NAME=app
      # below we give DB_user
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    # depends_on for one service to depend on another
    depends_on:
    # depends on starts the independent service first
    # it finds another service through service name which here is db
      - db


  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      # we will change the password with an encrypted password for production
      - POSTGRES_PASSWORD=supersecretpassword
